services:
  nginx:
    env_file:
      - ./envs/production/.env.proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "${CATWLK_PROXY_LETSENCRYPT_HOST_PATH:-/etc/letsencrypt}:/etc/letsencrypt:ro"
      - "${CATWLK_PROXY_ACME_WEBROOT_HOST_PATH:-/var/lib/letsencrypt}:/var/lib/letsencrypt:ro"
    deploy:
      replicas: ${MAKEPAD_PROXY_REPLICAS:-1}
      placement:
        constraints:
          - node.labels.infra.makepad.proxy == true
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first

networks:
  prod_app:
    external: true
    name: ${MAKEPAD_PROXY_PROD_APP_NETWORK}
  canary_app:
    external: true
    name: ${MAKEPAD_PROXY_CANARY_APP_NETWORK}
  alerteconso_prod_app:
    external: true
    name: ${MAKEPAD_PROXY_ALERTECONSO_APP_NETWORK}
