server {
    listen 80;
    listen [::]:80;
    server_name airloom.makepad.fr;
    resolver 127.0.0.11 valid=10s ipv6=off;
    location /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
        default_type text/plain;
    }
    location / {
        set $airloom_upstream http://airloom-prod-web:8080;
        proxy_pass $airloom_upstream;
        proxy_set_header Host $host;
    }
}
